INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('운전매너가 좋아요' , true);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('친절하고 매너가 좋아요' , true);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('깔끔해요' , true);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('시간약속을 잘 지켜요' , true);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('응답이 빨라요' , true);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('운전이 미숙해요' , false);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('불친절해요' , false);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('청결하지 않아요' , false);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('약속을 안 지켜요' , false);
INSERT INTO CHECKLIST (CHECK_CONTENT , CHECKPN ) VALUES ('응답이 느려요' , false);

-- INSERT INTO MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,GENDERS,PROVIDER_TYPE,MEMBER_STATUS,FUEL_TANK,POINT) VALUES ('test1@gmail.com','DJKD456!','HELLO','HI','MAN','NATIVE','MEMBER_ACTIVE',30.0,0);
-- INSERT INTO MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,GENDERS,PROVIDER_TYPE,MEMBER_STATUS,FUEL_TANK,POINT) VALUES ('test12@gmail.com','DJKD456!','HELLO','HI','MAN','NATIVE','MEMBER_ACTIVE',30.0,0);
-- INSERT INTO MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,GENDERS,PROVIDER_TYPE,MEMBER_STATUS,FUEL_TANK,POINT) VALUES ('test13@gmail.com','DJKD456!','HELLO','HI','MAN','NATIVE','MEMBER_ACTIVE',30.0,0);
--
-- insert into YATA (DEPARTURE_TIME, TIME_OF_ARRIVAL, TITLE, SPECIFICS, MAX_WAITING_TIME, YATA_STATUS, POST_STATUS, MAX_PEOPLE, AMOUNT,EMAIL) values ('2023-01-31T05:13:55', '2023-01-31T05:13:56', 'Mr', 'HELLO', 18,'YATA_NEOTA', 'POST_OPEN',1, 1871,'test1@gmail.com');

